In [2]:
## Import
import urllib.error
import urllib.request
import hockey_rink as hr
import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np

from PIL.EpsImagePlugin import split
from matplotlib.pyplot import legend

In [3]:
## import csv
csv_full = pd.read_csv("rawData/canada_v_hcd.csv")
csv_full

,Period,MatchClock,Timestamp,EventType,TeamStrengthType,TeamStrength,HomeGoalieOnIce,AwayGoalieOnIce,EventPosition,EventStartCoordinate,...,StartPlayerDirection3,StartPlayerDirection4,StartPlayerDirection5,StartPlayerDirection6,StartPlayerDirection7,StartPlayerDirection8,StartPlayerDirection9,StartPlayerDirection10,StartPlayerDirection11,StartPlayerDirection12
0,1,0,1.703790e+12,Faceoff,FullStrength,5v5,True,True,NeutralZone,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,1.703790e+12,PuckControl,FullStrength,5v5,True,True,NeutralZone,"-0.2,0.3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,0,1.703790e+12,PuckControl,FullStrength,5v5,True,True,NeutralZone,"-2.3,-0.1",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,1.703790e+12,PuckControl,FullStrength,5v5,True,True,NeutralZone,"-4.6,-0.8",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,1.703790e+12,BluelineCrossing,FullStrength,5v5,True,True,NeutralZone,"-7.1,-1.5",...,"-0.739,-0.674","0.992,-0.126","-0.919,0.394","-0.763,-0.647","-0.934,0.358","-0.953,0.302","0.371,-0.928","-0.275,0.961","-0.958,-0.287","-0.408,-0.913"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4477,3,1196,1.703800e+12,Shot,HomePowerplay,6v4,False,True,AwayTeamZone,"18.3,-6.5",...,"0.499,-0.867","0.76,-0.649","0.901,-0.433","0.933,0.361","0.332,-0.943","0.697,-0.717","0.909,-0.416","0.983,-0.182","0.312,-0.95",NaN
4478,3,1196,1.703800e+12,PuckControl,HomePowerplay,6v4,False,True,AwayTeamZone,"18.3,-6.5",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4479,3,1198,1.703800e+12,BluelineCrossing,HomePowerplay,6v4,False,True,AwayTeamZone,"7.2,15.1",...,"-0.67,0.743","-0.76,0.65","-0.35,0.937","-0.26,0.966","0.135,0.991","0.487,0.874","0.05,0.999","-0.746,0.666","-0.985,0.172",NaN
4480,3,1200,1.703800e+12,BluelineCrossing,EqualStrength,6v5,False,True,NeutralZone,"-7.1,15.1",...,"0.888,0.46","-0.92,0.393","0.685,-0.729","-0.977,-0.213","-0.981,0.192","0.091,-0.996","-0.706,0.709","-0.919,0.395","-0.969,-0.246",NaN
4481,3,1200,1.703800e+12,StoppageOfPlay,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Filter out only scenarios where powerplay
data = csv_full[(csv_full["TeamStrength"] == "5v4") | (csv_full["TeamStrength"] == "4v5")]
data

,Period,MatchClock,Timestamp,EventType,TeamStrengthType,TeamStrength,HomeGoalieOnIce,AwayGoalieOnIce,EventPosition,EventStartCoordinate,...,StartPlayerDirection3,StartPlayerDirection4,StartPlayerDirection5,StartPlayerDirection6,StartPlayerDirection7,StartPlayerDirection8,StartPlayerDirection9,StartPlayerDirection10,StartPlayerDirection11,StartPlayerDirection12
1252,1,1014,1.703790e+12,Faceoff,HomePowerplay,5v4,True,True,AwayTeamZone,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1253,1,1014,1.703790e+12,PuckControl,HomePowerplay,5v4,True,True,AwayTeamZone,"20.6,-5.4",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1254,1,1016,1.703790e+12,PuckControl,HomePowerplay,5v4,True,True,AwayTeamZone,"20,-6.5",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1255,1,1016,1.703790e+12,PuckControl,HomePowerplay,5v4,True,True,AwayTeamZone,"20.1,-6",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1256,1,1017,1.703790e+12,PuckControl,HomePowerplay,5v4,True,True,AwayTeamZone,"19.9,-6.4",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3657,3,584,1.703800e+12,Pass,AwayPowerplay,4v5,True,True,HomeTeamZone,"-25.8,-2.9",...,"-0.981,-0.192","-0.61,0.792","-1,0.002","-0.692,0.721","-0.938,0.347","-0.981,-0.196","-0.903,0.429","-0.933,-0.36","-0.103,-0.995",NaN
3658,3,584,1.703800e+12,PuckControl,AwayPowerplay,4v5,True,True,HomeTeamZone,"-25.6,-2.9",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3659,3,585,1.703800e+12,PuckControl,AwayPowerplay,4v5,True,True,HomeTeamZone,"-10.3,-1.5",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3660,3,586,1.703800e+12,Pass,AwayPowerplay,4v5,True,True,HomeTeamZone,"-12.7,0.1",...,"-0.645,0.764","-0.724,0.69","0.315,0.949","0.709,0.705","0.735,0.678","0.281,0.96","0.207,-0.978","0.372,0.928","0.089,-0.996",NaN
3661,3,586,1.703800e+12,PuckControl,AwayPowerplay,4v5,True,True,HomeTeamZone,"-12.9,0",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Can jump down to autoparse

In [4]:
blueline_rows = data[data["EventType"] == "BluelineCrossing"]
blueline_rows = blueline_rows.index
blueline_rows # list which contains the index number of every blueline row

shot_rows = data[data["EventType"] == "Shot"]
shot_rows = shot_rows.index
shot_rows = shot_rows.tolist()

In [5]:
bl_start_end = []
for index,value in enumerate(blueline_rows):
    if index == len(blueline_rows)-1:
        break
    bl_start_end.append(
        [value, int(blueline_rows[index+1])]
    )

bl_start_end
blueline_data = pd.DataFrame(bl_start_end, columns=["bl_start_index", "bl_end_index"])

In [6]:
#blueline_data["Start_matchclock"] = data[start]
for index, row_data in blueline_data.iterrows():
    st = data["MatchClock"][row_data["bl_start_index"]]
    blueline_data.loc[index,"start_matchClock"] = st

    en = data["MatchClock"][row_data["bl_end_index"]]
    blueline_data.loc[index, "end_matchClock"] = en

blueline_data["playtime_seconds"] = blueline_data['end_matchClock'] - blueline_data["start_matchClock"]

blueline_data = blueline_data[blueline_data["playtime_seconds"]>= 5]

blueline_data.reset_index(inplace= True, drop=True)
blueline_data

,bl_start_index,bl_end_index,start_matchClock,end_matchClock,playtime_seconds
0,1262,1271,1025.0,1035.0,10.0
1,1272,1289,1037.0,1049.0,12.0
2,1290,1295,1050.0,1063.0,13.0
3,1296,1306,1065.0,1073.0,8.0
4,1308,1313,1076.0,1082.0,6.0
5,1317,1355,1085.0,1119.0,34.0
6,1356,1364,1120.0,1130.0,10.0
7,1367,1422,1132.0,1193.0,61.0
8,1436,1445,2.0,8.0,6.0
9,1446,1463,9.0,29.0,20.0
10,1464,1476,30.0,39.0,9.0
11,1479,1490,41.0,49.0,8.0
12,1493,1507,51.0,63.0,12.0
13,1521,1532,73.0,79.0,6.0
14,1533,1674,81.0,206.0,125.0
15,1674,1682,206.0,213.0,7.0
16,1682,1714,213.0,237.0,24.0
17,1726,1767,248.0,283.0,35.0
18,1769,1776,286.0,295.0,9.0
19,1776,1782,295.0,300.0,5.0
20,1782,1796,300.0,309.0,9.0
21,1797,1804,311.0,316.0,5.0
22,1804,1912,316.0,379.0,63.0
23,1913,1914,380.0,385.0,5.0
24,1915,1925,386.0,394.0,8.0
25,1926,1943,396.0,417.0,21.0
26,1945,1962,419.0,431.0,12.0
27,1963,1969,431.0,440.0,9.0
28,1969,2515,440.0,846.0,406.0
29,2518,2531,850.0,862.0,12.0
30,2536,2569,864.0,887.0,23.0
31,2569,2575,887.0,896.0,9.0
32,2575,2641,896.0,948.0,52.0
33,3213,3221,189.0,203.0,14.0
34,3225,3236,206.0,216.0,10.0
35,3237,3253,218.0,235.0,17.0
36,3261,3271,238.0,244.0,6.0
37,3280,3528,250.0,477.0,227.0
38,3529,3533,478.0,486.0,8.0
39,3539,3608,490.0,537.0,47.0
40,3608,3613,537.0,547.0,10.0
41,3622,3627,552.0,561.0,9.0
42,3633,4305,565.0,1087.0,522.0
43,4306,4315,1088.0,1096.0,8.0
44,4316,4390,1098.0,1138.0,40.0
45,4391,4393,1139.0,1147.0,8.0
46,4400,4479,1151.0,1198.0,47.0

In [7]:
## shots
# Create intervals from the start and end indices
intervals = pd.IntervalIndex.from_arrays(
    blueline_data["bl_start_index"],
    blueline_data["bl_end_index"],
    closed="neither", # greater than start and less than end
)

# Check if any shot falls inside each interval
shot_mask = pd.Series(
    [any(s in interval for s in shot_rows) for interval in intervals],
    index=blueline_data.index,)

blueline_data = blueline_data[shot_mask]
blueline_data

,bl_start_index,bl_end_index,start_matchClock,end_matchClock,playtime_seconds
1,1272,1289,1037.0,1049.0,12.0
5,1317,1355,1085.0,1119.0,34.0
13,1521,1532,73.0,79.0,6.0
14,1533,1674,81.0,206.0,125.0
18,1769,1776,286.0,295.0,9.0
20,1782,1796,300.0,309.0,9.0
22,1804,1912,316.0,379.0,63.0
24,1915,1925,386.0,394.0,8.0
28,1969,2515,440.0,846.0,406.0
30,2536,2569,864.0,887.0,23.0
32,2575,2641,896.0,948.0,52.0
35,3237,3253,218.0,235.0,17.0
39,3539,3608,490.0,537.0,47.0
44,4316,4390,1098.0,1138.0,40.0
46,4400,4479,1151.0,1198.0,47.0

Filter by examples that include a shot, split ones which have multiple shots, takes place in opponents endzone

In [8]:
#will afterwards needs to change this to either be a loop or an apply() function

single_row = blueline_data.loc[3]
structure = data.loc[single_row["bl_start_index"]:single_row["bl_end_index"]]
#if "Shot" in structure["EventType"]:

KeyError: 3

## new direction - New Autoparse
- go to each shot
- go backwards 5 seconds or until you get a faceoff or blueline crossing
    - if uninteruped, caputure that as a successful scenario
- repeat

In [ ]:
## just make sure to ingest the entire CSV first.

shot_rows = data[data["EventType"] == "Shot"]
shot_rows = shot_rows.index
shot_rows = shot_rows.tolist()

In [ ]:
n_seconds = 5
scenario_number = 1
game_name = "Fribourg-HC_Dynamo"

for single_shot in shot_rows:
    clock_at_shot = data.loc[single_shot, "MatchClock"]
    period = data.loc[single_shot, "Period"]
    play_data = data[(data["MatchClock"] >= clock_at_shot - n_seconds) & (data["MatchClock"] <= clock_at_shot) & (data["Period"] == period)] #accesses data which occurs n_seconds prior to shot event.


    if ("BluelineCrossing" in play_data["EventType"].values) | ("Faceoff" in play_data["EventType"].values): #removes scenarios which break structure rules.
        print("found BluelineCrossing or Faceoff. No export")
        continue

    else:
        play_data.to_csv(f"autoparse_csv/{game_name}_shotData{scenario_number}.csv") #exports scenarios which fit structure rules.
        print(f"Exported Scenario {scenario_number} to CSV")
        scenario_number = scenario_number+1

Bug: Bug Fix: CSV Fribourg CSV2 only 2 seconds of time?